spring:
  config:
    activate:
      on-profile: redis-local, redis-test
  redis:
    host: localhost
    port: 6379


---
spring:
  config:
    activate:
      on-profile: redis-prod
  redis:
    host: localhost
    port: 6379


